 # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          # Optionally load Supabase secrets from repository secrets
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          # Enable LangGraph / OpenAI-driven agent in CI when explicitly set in repository secrets.
          # Set LANGGRAPH_ENABLED to '1' / 'true' to allow the workflow to construct the real agent
          # (requires OPENAI_API_KEY also present as a secret).
          AGENT_USE_LANGGRAPH: ${{ secrets.LANGGRAPH_ENABLED }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          PYTHONPATH=. pytest -q

  integration:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Integration tests (guarded by secrets)
        run: |
          set -e
          OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}'
          SUPABASE_SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
          SUPABASE_URL='${{ secrets.SUPABASE_URL }}'
          AGENT_USE_LANGGRAPH="${{ secrets.LANGGRAPH_ENABLED }}"

          if [ -z "$OPENAI_API_KEY" ] || [ -z "$SUPABASE_SERVICE_ROLE_KEY" ] || [ -z "$SUPABASE_URL" ]; then
            echo "Required secrets not available — skipping integration tests."
            exit 0
          fi

          PYTHONPATH=. \
          OPENAI_API_KEY="$OPENAI_API_KEY" \
          SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY" \
          SUPABASE_URL="$SUPABASE_URL" \
          AGENT_USE_LANGGRAPH="${AGENT_USE_LANGGRAPH:-0}" \
          pytest -q -m integration
