name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          # Optionally load Supabase secrets from repository secrets
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          # Enable LangGraph / OpenAI-driven agent in CI when explicitly set in repository secrets.
          # Set LANGGRAPH_ENABLED to '1' / 'true' to allow the workflow to construct the real agent
          # (requires OPENAI_API_KEY also present as a secret).
          AGENT_USE_LANGGRAPH: ${{ secrets.LANGGRAPH_ENABLED }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          PYTHONPATH=. pytest -q

  integration:
    if: ${{ secrets.LANGGRAPH_ENABLED }}
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration tests (LangGraph/OpenAI)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AGENT_USE_LANGGRAPH: ${{ secrets.LANGGRAPH_ENABLED }}
        run: |
          PYTHONPATH=. AGENT_USE_LANGGRAPH=1 pytest -q -m integration
